/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/board/Board.vue')['default']
    Column: typeof import('./src/components/column/Column.vue')['default']
    CommonButton: typeof import('./src/components/common/CommonButton.vue')['default']
    CommonTag: typeof import('./src/components/common/CommonTag.vue')['default']
    CommonWrapper: typeof import('./src/components/common/CommonWrapper.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/header/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideTask: typeof import('./src/components/task/SideTask.vue')['default']
    Task: typeof import('./src/components/task/Task.vue')['default']
  }
}
